spring:
  application:
    name: provide-serivce
  zipkin:
    base-url: http://127.0.0.1:80
  sleuth:
    sampler:
      percentage: 0.05

swagger:
  title: provide-service api 文档
  description: 测试
  version: 3.0
server:
  port: 8000

eureka:
  instance:
    #swagger把这个功能集成到Eureka中，
    #点击具体服务的时候会跳到swagger页面去
    status-page-url : http://localhost:8000/swagger-ui.html
  client:
    service-url:
      ##eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://zfh:zfh@localhost:8761/eureka/
    #由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    #fetch-registry: false

############### admin 2.0##########################
spring.boot.admin.client.url: http://localhost:8863
#默认大部分的endpoint是没有开放，所以要公开这些endpoint
management.endpoints.web.exposure.include: '*'
endpoint.health.show-details: ALWAYS
management:
  security:
    enabled: false
  #写入日志文件的目标。启用日志文件执行器端点(值先随便写)
logging.file: eq

#logging.pattern.file: %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
############### admin 2.0##########################





