spring:
  application:
    name: provide-serivce
  zipkin:
    base-url: http://127.0.0.1:80
  sleuth:
    sampler:
      percentage: 0.05
server:
  port: 8000

eureka:
  instance:
    #swagger把这个功能集成到Eureka中，
    #点击具体服务的时候会跳到swagger页面去
    status-page-url : http://localhost:8000/swagger-ui.html
  client:
    service-url:
      ##eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://zfh:zfh@localhost:8761/eureka/
    #由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    #fetch-registry: false






