server.port : 8762
spring.application.name: server-slave

############### admin 2.0##########################
spring.boot.admin.client.url: http://localhost:8863
#默认大部分的endpoint是没有开放，所以要公开这些endpoint
management.endpoints.web.exposure.include: '*'
endpoint.health.show-details: ALWAYS
management:
  security:
    enabled: false
logging.file: /var/c/sample-boot-application.log

#logging.pattern.file: %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
############### admin 2.0##########################



#eureka.environment=dev
#注册中心默认端口就是8761，也可通过下面的方式定义其他端口
eureka.client.serviceUrl.defaultZone: http://zfh:zfh@localhost:8762/eureka/

# 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
#eureka.client.register-with-eureka=false

# 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
# eureka.client.fetch-registry=false

# 关闭自我保护
# eureka.server.enableSelfPreservation=false

#swagger把这个功能集成到Eureka中，
#点击具体服务的时候会跳到swagger页面去
#eureka.instance.status-page-url=http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

# 指定不同的环境
#spring.profiles.active=master

#eureka 设置安全限制
#开启认证
security.basic.enabled: true
#用户名
security.user.name: zfh
#密码
security.user.password: zfh

# Enable admin features for the application.
#spring.application.admin.enabled=false