spring:
  application:
    name: consume-serivce
  zipkin:
    base-url: http://localhost:80
    locator:
      discovery:
        enabled: true


server:
  port: 8001

eureka:
  client:
    service-url:
      ##eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://localhost:8761/eureka/
    #由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    #fetch-registry: false



