spring:
  application:
    name: consume-serivce
  zipkin:
     base-url: http://127.0.0.1:80
  sleuth:
     sampler:
       percentage: 0.05


server:
  port: 8001

eureka:
  client:
    service-url:
      ##eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://zfh:zfh@localhost:8761/eureka/
    #由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    #fetch-registry: false

    #注册中心开启认证后，项目中的注册中心地址的配置也需要改变,需要加上认证的用户名和密码
    #eureka.client.serviceUrl.defaultZone=http://用户名:密码@ip:port/eureka/

# hystrix的超时时间必须大于ribbon的超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 开启重试
zuul.retryable: true
spring.cloud.loadbalancer.retry.enabled: true
# 请求连接的超时时间
ribbon.connectTimeout: 2000
# 请求处理的超时时间
ribbon.readTimeout: 5000
# 对当前实例的重试次数
ribbon.maxAutoRetries: 1
# 切换实例的重试次数
ribbon.maxAutoRetriesNextServer: 3
# 对所有操作请求都进行重试
ribbon.okToRetryOnAllOperations: sstrue






#auth
#server.session.cookie.name : OAUTH2SESSION
#security.oauth2.client.client-id: zfh1
#security.oauth2.client.client-secret: zfh
#security.oauth2.client.access-token-uri: http://localhost:8003/oauth/token
#security.oauth2.client.user-authorization-uri: http://localhost:8003/oauth/authorize
#security.oauth2.client.client-authentication-scheme: query
#logging.level.root: info
